#一下是单节点的配置
spring:
  application:
    name: ad-eureka
server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    # 表示是否从Eureka Server获取注册信息，默认为true。如果这是一个单点的Eureka Server，不需要同步其他节点的数据，则设置为false
    fetch-registry: false
    # 表示是否将自己注册到Eureka Server，默认为true。由于当前节点就是Eureka Server，故设置为false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#修改了配置之后，代码重新编译打包才有效，需要执行命令：mvn clean package -Dmaven.test.skip=true -U
---
spring:
  application:
    name: ad-eureka
  profiles: server1
server:
  port: 8000
eureka:
  instance:
    hostname: server1
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server2:8001/eureka/,http://server3:8002/eureka/

---
spring:
  application:
    name: ad-eureka
  profiles: server2
server:
  port: 8001
eureka:
  instance:
    hostname: server2
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/,http://server3:8002/eureka/

---
spring:
  application:
    name: ad-eureka
  profiles: server3
server:
  port: 8002
eureka:
  instance:
    hostname: server3
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/,http://server2:8001/eureka/